/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model;


import jooqDemo.model.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account extends SchemaImpl {

    private static final long serialVersionUID = 1968187800;

    /**
     * The reference instance of <code>account</code>
     */
    public static final Account ACCOUNT = new Account();

    /**
     * The table <code>account.bankBranch</code>.
     */
    public final Bankbranch BANKBRANCH = jooqDemo.model.tables.Bankbranch.BANKBRANCH;

    /**
     * The table <code>account.bankCode</code>.
     */
    public final Bankcode BANKCODE = jooqDemo.model.tables.Bankcode.BANKCODE;

    /**
     * The table <code>account.card</code>.
     */
    public final Card CARD = jooqDemo.model.tables.Card.CARD;

    /**
     * The table <code>account.cardVerify</code>.
     */
    public final Cardverify CARDVERIFY = jooqDemo.model.tables.Cardverify.CARDVERIFY;

    /**
     * The table <code>account.cityCode</code>.
     */
    public final Citycode CITYCODE = jooqDemo.model.tables.Citycode.CITYCODE;

    /**
     * The table <code>account.ddAccount</code>.
     */
    public final Ddaccount DDACCOUNT = jooqDemo.model.tables.Ddaccount.DDACCOUNT;

    /**
     * The table <code>account.ddRate</code>.
     */
    public final Ddrate DDRATE = jooqDemo.model.tables.Ddrate.DDRATE;

    /**
     * The table <code>account.ddRemark</code>.
     */
    public final Ddremark DDREMARK = jooqDemo.model.tables.Ddremark.DDREMARK;

    /**
     * The table <code>account.ddType</code>.
     */
    public final Ddtype DDTYPE = jooqDemo.model.tables.Ddtype.DDTYPE;

    /**
     * The table <code>account.fdAccount</code>.
     */
    public final Fdaccount FDACCOUNT = jooqDemo.model.tables.Fdaccount.FDACCOUNT;

    /**
     * The table <code>account.fdAccountOTP</code>.
     */
    public final Fdaccountotp FDACCOUNTOTP = jooqDemo.model.tables.Fdaccountotp.FDACCOUNTOTP;

    /**
     * The table <code>account.pattern</code>.
     */
    public final Pattern PATTERN = jooqDemo.model.tables.Pattern.PATTERN;

    /**
     * The table <code>account.payee</code>.
     */
    public final Payee PAYEE = jooqDemo.model.tables.Payee.PAYEE;

    /**
     * The table <code>account.payment</code>.
     */
    public final Payment PAYMENT = jooqDemo.model.tables.Payment.PAYMENT;

    /**
     * The table <code>account.paymentReport</code>.
     */
    public final Paymentreport PAYMENTREPORT = jooqDemo.model.tables.Paymentreport.PAYMENTREPORT;

    /**
     * The table <code>account.paymentRequest</code>.
     */
    public final Paymentrequest PAYMENTREQUEST = jooqDemo.model.tables.Paymentrequest.PAYMENTREQUEST;

    /**
     * No further instances allowed
     */
    private Account() {
        super("account", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Bankbranch.BANKBRANCH,
            Bankcode.BANKCODE,
            Card.CARD,
            Cardverify.CARDVERIFY,
            Citycode.CITYCODE,
            Ddaccount.DDACCOUNT,
            Ddrate.DDRATE,
            Ddremark.DDREMARK,
            Ddtype.DDTYPE,
            Fdaccount.FDACCOUNT,
            Fdaccountotp.FDACCOUNTOTP,
            Pattern.PATTERN,
            Payee.PAYEE,
            Payment.PAYMENT,
            Paymentreport.PAYMENTREPORT,
            Paymentrequest.PAYMENTREQUEST);
    }
}
