/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model;


import javax.annotation.Generated;

import jooqDemo.model.tables.Table1;
import jooqDemo.model.tables.records.Table1Record;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>mydata</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<Table1Record, Integer> IDENTITY_TABLE1 = Identities0.IDENTITY_TABLE1;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Table1Record> KEY_TABLE1_PRIMARY = UniqueKeys0.KEY_TABLE1_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<Table1Record, Integer> IDENTITY_TABLE1 = createIdentity(Table1.TABLE1, Table1.TABLE1.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<Table1Record> KEY_TABLE1_PRIMARY = createUniqueKey(Table1.TABLE1, "KEY_table1_PRIMARY", Table1.TABLE1.ID);
    }
}
