/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooqDemo.model.tables.Table1;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mydata extends SchemaImpl {

    private static final long serialVersionUID = -1884206338;

    /**
     * The reference instance of <code>mydata</code>
     */
    public static final Mydata MYDATA = new Mydata();

    /**
     * The table <code>mydata.table1</code>.
     */
    public final Table1 TABLE1 = jooqDemo.model.tables.Table1.TABLE1;

    /**
     * No further instances allowed
     */
    private Mydata() {
        super("mydata", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Table1.TABLE1);
    }
}
