/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model;


import javax.annotation.Generated;

import jooqDemo.model.tables.Table1;


/**
 * Convenience access to all tables in mydata
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mydata.table1</code>.
     */
    public static final Table1 TABLE1 = jooqDemo.model.tables.Table1.TABLE1;
}
