/*
 * This file is generated by jOOQ.
*/
package citad.model;


import citad.model.tables.BankNhanCitab;
import citad.model.tables.Bankbranch;
import citad.model.tables.Bankcitad;
import citad.model.tables.Bankcitadbranch;
import citad.model.tables.Bankcitadcity;
import citad.model.tables.Bankcode;
import citad.model.tables.Banknapas;
import citad.model.tables.Citycode;
import citad.model.tables.Customertype;
import citad.model.tables.Ddtransaction;
import citad.model.tables.Fdaccount;
import citad.model.tables.Fdrate;
import citad.model.tables.Fdtrans;
import citad.model.tables.Fdtype;
import citad.model.tables.Fee;
import citad.model.tables.Loandescription;
import citad.model.tables.Paymentschedule;
import citad.model.tables.Products;
import citad.model.tables.Producttype;
import citad.model.tables.Scheduleconfig;
import citad.model.tables.Services;
import citad.model.tables.Timeline;
import citad.model.tables.Transaction;
import citad.model.tables.Transactionrule;
import citad.model.tables.Transactiontype;
import citad.model.tables.Transverify;
import citad.model.tables.Updatepaymentschedule;
import citad.model.tables.Userdatacontext;
import citad.model.tables.Userloans;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in transaction
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>transaction.bankBranch</code>.
     */
    public static final Bankbranch BANKBRANCH = citad.model.tables.Bankbranch.BANKBRANCH;

    /**
     * The table <code>transaction.bankCitad</code>.
     */
    public static final Bankcitad BANKCITAD = citad.model.tables.Bankcitad.BANKCITAD;

    /**
     * The table <code>transaction.bankCitadBranch</code>.
     */
    public static final Bankcitadbranch BANKCITADBRANCH = citad.model.tables.Bankcitadbranch.BANKCITADBRANCH;

    /**
     * The table <code>transaction.bankCitadCity</code>.
     */
    public static final Bankcitadcity BANKCITADCITY = citad.model.tables.Bankcitadcity.BANKCITADCITY;

    /**
     * The table <code>transaction.bankCode</code>.
     */
    public static final Bankcode BANKCODE = citad.model.tables.Bankcode.BANKCODE;

    /**
     * The table <code>transaction.bankNapas</code>.
     */
    public static final Banknapas BANKNAPAS = citad.model.tables.Banknapas.BANKNAPAS;

    /**
     * The table <code>transaction.bank_nhan_citab</code>.
     */
    public static final BankNhanCitab BANK_NHAN_CITAB = citad.model.tables.BankNhanCitab.BANK_NHAN_CITAB;

    /**
     * The table <code>transaction.cityCode</code>.
     */
    public static final Citycode CITYCODE = citad.model.tables.Citycode.CITYCODE;

    /**
     * The table <code>transaction.customerType</code>.
     */
    public static final Customertype CUSTOMERTYPE = citad.model.tables.Customertype.CUSTOMERTYPE;

    /**
     * The table <code>transaction.ddTransaction</code>.
     */
    public static final Ddtransaction DDTRANSACTION = citad.model.tables.Ddtransaction.DDTRANSACTION;

    /**
     * The table <code>transaction.fdAccount</code>.
     */
    public static final Fdaccount FDACCOUNT = citad.model.tables.Fdaccount.FDACCOUNT;

    /**
     * The table <code>transaction.fdRate</code>.
     */
    public static final Fdrate FDRATE = citad.model.tables.Fdrate.FDRATE;

    /**
     * The table <code>transaction.fdTrans</code>.
     */
    public static final Fdtrans FDTRANS = citad.model.tables.Fdtrans.FDTRANS;

    /**
     * The table <code>transaction.fdType</code>.
     */
    public static final Fdtype FDTYPE = citad.model.tables.Fdtype.FDTYPE;

    /**
     * The table <code>transaction.fee</code>.
     */
    public static final Fee FEE = citad.model.tables.Fee.FEE;

    /**
     * The table <code>transaction.loanDescription</code>.
     */
    public static final Loandescription LOANDESCRIPTION = citad.model.tables.Loandescription.LOANDESCRIPTION;

    /**
     * The table <code>transaction.paymentSchedule</code>.
     */
    public static final Paymentschedule PAYMENTSCHEDULE = citad.model.tables.Paymentschedule.PAYMENTSCHEDULE;

    /**
     * The table <code>transaction.products</code>.
     */
    public static final Products PRODUCTS = citad.model.tables.Products.PRODUCTS;

    /**
     * The table <code>transaction.productType</code>.
     */
    public static final Producttype PRODUCTTYPE = citad.model.tables.Producttype.PRODUCTTYPE;

    /**
     * The table <code>transaction.scheduleConfig</code>.
     */
    public static final Scheduleconfig SCHEDULECONFIG = citad.model.tables.Scheduleconfig.SCHEDULECONFIG;

    /**
     * The table <code>transaction.services</code>.
     */
    public static final Services SERVICES = citad.model.tables.Services.SERVICES;

    /**
     * The table <code>transaction.timeLine</code>.
     */
    public static final Timeline TIMELINE = citad.model.tables.Timeline.TIMELINE;

    /**
     * The table <code>transaction.transaction</code>.
     */
    public static final Transaction TRANSACTION_ = citad.model.tables.Transaction.TRANSACTION_;

    /**
     * The table <code>transaction.transactionRule</code>.
     */
    public static final Transactionrule TRANSACTIONRULE = citad.model.tables.Transactionrule.TRANSACTIONRULE;

    /**
     * The table <code>transaction.transactionType</code>.
     */
    public static final Transactiontype TRANSACTIONTYPE = citad.model.tables.Transactiontype.TRANSACTIONTYPE;

    /**
     * The table <code>transaction.transVerify</code>.
     */
    public static final Transverify TRANSVERIFY = citad.model.tables.Transverify.TRANSVERIFY;

    /**
     * The table <code>transaction.updatePaymentSchedule</code>.
     */
    public static final Updatepaymentschedule UPDATEPAYMENTSCHEDULE = citad.model.tables.Updatepaymentschedule.UPDATEPAYMENTSCHEDULE;

    /**
     * The table <code>transaction.userDataContext</code>.
     */
    public static final Userdatacontext USERDATACONTEXT = citad.model.tables.Userdatacontext.USERDATACONTEXT;

    /**
     * The table <code>transaction.userLoans</code>.
     */
    public static final Userloans USERLOANS = citad.model.tables.Userloans.USERLOANS;
}
