/*
 * This file is generated by jOOQ.
*/
package citad.model.tables;


import citad.model.Transaction;
import citad.model.tables.records.BankNhanCitabRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankNhanCitab extends TableImpl<BankNhanCitabRecord> {

    private static final long serialVersionUID = 2085731779;

    /**
     * The reference instance of <code>transaction.bank_nhan_citab</code>
     */
    public static final BankNhanCitab BANK_NHAN_CITAB = new BankNhanCitab();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BankNhanCitabRecord> getRecordType() {
        return BankNhanCitabRecord.class;
    }

    /**
     * The column <code>transaction.bank_nhan_citab.tinh</code>.
     */
    public final TableField<BankNhanCitabRecord, String> TINH = createField("tinh", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

    /**
     * The column <code>transaction.bank_nhan_citab.nganhang</code>.
     */
    public final TableField<BankNhanCitabRecord, String> NGANHANG = createField("nganhang", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

    /**
     * The column <code>transaction.bank_nhan_citab.chinhanh</code>.
     */
    public final TableField<BankNhanCitabRecord, String> CHINHANH = createField("chinhanh", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

    /**
     * The column <code>transaction.bank_nhan_citab.directbank</code>.
     */
    public final TableField<BankNhanCitabRecord, String> DIRECTBANK = createField("directbank", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * Create a <code>transaction.bank_nhan_citab</code> table reference
     */
    public BankNhanCitab() {
        this("bank_nhan_citab", null);
    }

    /**
     * Create an aliased <code>transaction.bank_nhan_citab</code> table reference
     */
    public BankNhanCitab(String alias) {
        this(alias, BANK_NHAN_CITAB);
    }

    private BankNhanCitab(String alias, Table<BankNhanCitabRecord> aliased) {
        this(alias, aliased, null);
    }

    private BankNhanCitab(String alias, Table<BankNhanCitabRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Transaction.TRANSACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankNhanCitab as(String alias) {
        return new BankNhanCitab(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BankNhanCitab rename(String name) {
        return new BankNhanCitab(name, null);
    }
}
