/*
 * This file is generated by jOOQ.
*/
package citad.model.tables;


import citad.model.Keys;
import citad.model.Transaction;
import citad.model.tables.records.BanknapasRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Banknapas extends TableImpl<BanknapasRecord> {

    private static final long serialVersionUID = -818543065;

    /**
     * The reference instance of <code>transaction.bankNapas</code>
     */
    public static final Banknapas BANKNAPAS = new Banknapas();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BanknapasRecord> getRecordType() {
        return BanknapasRecord.class;
    }

    /**
     * The column <code>transaction.bankNapas.bankId</code>.
     */
    public final TableField<BanknapasRecord, String> BANKID = createField("bankId", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>transaction.bankNapas.bankName</code>.
     */
    public final TableField<BanknapasRecord, String> BANKNAME = createField("bankName", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>transaction.bankNapas.typeTransfer</code>.
     */
    public final TableField<BanknapasRecord, String> TYPETRANSFER = createField("typeTransfer", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * Create a <code>transaction.bankNapas</code> table reference
     */
    public Banknapas() {
        this("bankNapas", null);
    }

    /**
     * Create an aliased <code>transaction.bankNapas</code> table reference
     */
    public Banknapas(String alias) {
        this(alias, BANKNAPAS);
    }

    private Banknapas(String alias, Table<BanknapasRecord> aliased) {
        this(alias, aliased, null);
    }

    private Banknapas(String alias, Table<BanknapasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Transaction.TRANSACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BanknapasRecord> getPrimaryKey() {
        return Keys.KEY_BANKNAPAS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BanknapasRecord>> getKeys() {
        return Arrays.<UniqueKey<BanknapasRecord>>asList(Keys.KEY_BANKNAPAS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Banknapas as(String alias) {
        return new Banknapas(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Banknapas rename(String name) {
        return new Banknapas(name, null);
    }
}
