/*
 * This file is generated by jOOQ.
*/
package citad.model.tables.records;


import citad.model.tables.Bankcitadbranch;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankcitadbranchRecord extends UpdatableRecordImpl<BankcitadbranchRecord> implements Record11<Integer, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 462974463;

    /**
     * Setter for <code>transaction.bankCitadBranch.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.bankCitadBranch.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>transaction.bankCitadBranch.directBankID</code>.
     */
    public void setDirectbankid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.bankCitadBranch.directBankID</code>.
     */
    public String getDirectbankid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>transaction.bankCitadBranch.directBankName</code>.
     */
    public void setDirectbankname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.bankCitadBranch.directBankName</code>.
     */
    public String getDirectbankname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>transaction.bankCitadBranch.directBankNameANSI</code>.
     */
    public void setDirectbanknameansi(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>transaction.bankCitadBranch.directBankNameANSI</code>.
     */
    public String getDirectbanknameansi() {
        return (String) get(3);
    }

    /**
     * Setter for <code>transaction.bankCitadBranch.indirectBankId</code>.
     */
    public void setIndirectbankid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>transaction.bankCitadBranch.indirectBankId</code>.
     */
    public String getIndirectbankid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>transaction.bankCitadBranch.indirectBankName</code>.
     */
    public void setIndirectbankname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>transaction.bankCitadBranch.indirectBankName</code>.
     */
    public String getIndirectbankname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>transaction.bankCitadBranch.indirectBankNameANSI</code>.
     */
    public void setIndirectbanknameansi(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>transaction.bankCitadBranch.indirectBankNameANSI</code>.
     */
    public String getIndirectbanknameansi() {
        return (String) get(6);
    }

    /**
     * Setter for <code>transaction.bankCitadBranch.formalName</code>.
     */
    public void setFormalname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>transaction.bankCitadBranch.formalName</code>.
     */
    public String getFormalname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>transaction.bankCitadBranch.routeCode</code>.
     */
    public void setRoutecode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>transaction.bankCitadBranch.routeCode</code>.
     */
    public String getRoutecode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>transaction.bankCitadBranch.offsetAcc</code>.
     */
    public void setOffsetacc(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>transaction.bankCitadBranch.offsetAcc</code>.
     */
    public String getOffsetacc() {
        return (String) get(9);
    }

    /**
     * Setter for <code>transaction.bankCitadBranch.branchType</code>.
     */
    public void setBranchtype(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>transaction.bankCitadBranch.branchType</code>.
     */
    public String getBranchtype() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Bankcitadbranch.BANKCITADBRANCH.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Bankcitadbranch.BANKCITADBRANCH.DIRECTBANKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Bankcitadbranch.BANKCITADBRANCH.DIRECTBANKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Bankcitadbranch.BANKCITADBRANCH.DIRECTBANKNAMEANSI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Bankcitadbranch.BANKCITADBRANCH.INDIRECTBANKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Bankcitadbranch.BANKCITADBRANCH.INDIRECTBANKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Bankcitadbranch.BANKCITADBRANCH.INDIRECTBANKNAMEANSI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Bankcitadbranch.BANKCITADBRANCH.FORMALNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Bankcitadbranch.BANKCITADBRANCH.ROUTECODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Bankcitadbranch.BANKCITADBRANCH.OFFSETACC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Bankcitadbranch.BANKCITADBRANCH.BRANCHTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDirectbankid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDirectbankname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDirectbanknameansi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIndirectbankid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIndirectbankname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getIndirectbanknameansi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getFormalname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRoutecode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getOffsetacc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getBranchtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord value2(String value) {
        setDirectbankid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord value3(String value) {
        setDirectbankname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord value4(String value) {
        setDirectbanknameansi(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord value5(String value) {
        setIndirectbankid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord value6(String value) {
        setIndirectbankname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord value7(String value) {
        setIndirectbanknameansi(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord value8(String value) {
        setFormalname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord value9(String value) {
        setRoutecode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord value10(String value) {
        setOffsetacc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord value11(String value) {
        setBranchtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadbranchRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BankcitadbranchRecord
     */
    public BankcitadbranchRecord() {
        super(Bankcitadbranch.BANKCITADBRANCH);
    }

    /**
     * Create a detached, initialised BankcitadbranchRecord
     */
    public BankcitadbranchRecord(Integer id, String directbankid, String directbankname, String directbanknameansi, String indirectbankid, String indirectbankname, String indirectbanknameansi, String formalname, String routecode, String offsetacc, String branchtype) {
        super(Bankcitadbranch.BANKCITADBRANCH);

        set(0, id);
        set(1, directbankid);
        set(2, directbankname);
        set(3, directbanknameansi);
        set(4, indirectbankid);
        set(5, indirectbankname);
        set(6, indirectbanknameansi);
        set(7, formalname);
        set(8, routecode);
        set(9, offsetacc);
        set(10, branchtype);
    }
}
