/*
 * This file is generated by jOOQ.
*/
package citad.model.tables.records;


import citad.model.tables.Bankcitad;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankcitadRecord extends UpdatableRecordImpl<BankcitadRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = -867814924;

    /**
     * Setter for <code>transaction.bankCitad.bankId</code>.
     */
    public void setBankid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.bankCitad.bankId</code>.
     */
    public String getBankid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>transaction.bankCitad.bankName</code>.
     */
    public void setBankname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.bankCitad.bankName</code>.
     */
    public String getBankname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>transaction.bankCitad.formalName</code>.
     */
    public void setFormalname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.bankCitad.formalName</code>.
     */
    public String getFormalname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>transaction.bankCitad.napas</code>.
     */
    public void setNapas(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>transaction.bankCitad.napas</code>.
     */
    public String getNapas() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Bankcitad.BANKCITAD.BANKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Bankcitad.BANKCITAD.BANKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Bankcitad.BANKCITAD.FORMALNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Bankcitad.BANKCITAD.NAPAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getBankid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBankname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFormalname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNapas();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadRecord value1(String value) {
        setBankid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadRecord value2(String value) {
        setBankname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadRecord value3(String value) {
        setFormalname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadRecord value4(String value) {
        setNapas(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BankcitadRecord
     */
    public BankcitadRecord() {
        super(Bankcitad.BANKCITAD);
    }

    /**
     * Create a detached, initialised BankcitadRecord
     */
    public BankcitadRecord(String bankid, String bankname, String formalname, String napas) {
        super(Bankcitad.BANKCITAD);

        set(0, bankid);
        set(1, bankname);
        set(2, formalname);
        set(3, napas);
    }
}
