/*
 * This file is generated by jOOQ.
*/
package citad.model.tables.records;


import citad.model.tables.Banknapas;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BanknapasRecord extends UpdatableRecordImpl<BanknapasRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -49188641;

    /**
     * Setter for <code>transaction.bankNapas.bankId</code>.
     */
    public void setBankid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.bankNapas.bankId</code>.
     */
    public String getBankid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>transaction.bankNapas.bankName</code>.
     */
    public void setBankname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.bankNapas.bankName</code>.
     */
    public String getBankname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>transaction.bankNapas.typeTransfer</code>.
     */
    public void setTypetransfer(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.bankNapas.typeTransfer</code>.
     */
    public String getTypetransfer() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Banknapas.BANKNAPAS.BANKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Banknapas.BANKNAPAS.BANKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Banknapas.BANKNAPAS.TYPETRANSFER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getBankid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBankname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTypetransfer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BanknapasRecord value1(String value) {
        setBankid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BanknapasRecord value2(String value) {
        setBankname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BanknapasRecord value3(String value) {
        setTypetransfer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BanknapasRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BanknapasRecord
     */
    public BanknapasRecord() {
        super(Banknapas.BANKNAPAS);
    }

    /**
     * Create a detached, initialised BanknapasRecord
     */
    public BanknapasRecord(String bankid, String bankname, String typetransfer) {
        super(Banknapas.BANKNAPAS);

        set(0, bankid);
        set(1, bankname);
        set(2, typetransfer);
    }
}
