/*
 * This file is generated by jOOQ.
*/
package citad.model.tables.records;


import citad.model.tables.Bankcitadcity;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankcitadcityRecord extends UpdatableRecordImpl<BankcitadcityRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1561288642;

    /**
     * Setter for <code>transaction.bankCitadCity.cityId</code>.
     */
    public void setCityid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.bankCitadCity.cityId</code>.
     */
    public String getCityid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>transaction.bankCitadCity.cityName</code>.
     */
    public void setCityname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.bankCitadCity.cityName</code>.
     */
    public String getCityname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Bankcitadcity.BANKCITADCITY.CITYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Bankcitadcity.BANKCITADCITY.CITYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCityname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadcityRecord value1(String value) {
        setCityid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadcityRecord value2(String value) {
        setCityname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankcitadcityRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BankcitadcityRecord
     */
    public BankcitadcityRecord() {
        super(Bankcitadcity.BANKCITADCITY);
    }

    /**
     * Create a detached, initialised BankcitadcityRecord
     */
    public BankcitadcityRecord(String cityid, String cityname) {
        super(Bankcitadcity.BANKCITADCITY);

        set(0, cityid);
        set(1, cityname);
    }
}
