/*
 * This file is generated by jOOQ.
*/
package citad.model.tables.records;


import citad.model.tables.Updatepaymentschedule;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpdatepaymentscheduleRecord extends UpdatableRecordImpl<UpdatepaymentscheduleRecord> implements Record20<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Integer, Integer, Long, Long, Integer> {

    private static final long serialVersionUID = -1082552651;

    /**
     * Setter for <code>transaction.updatePaymentSchedule.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.cif</code>.
     */
    public void setCif(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.cif</code>.
     */
    public String getCif() {
        return (String) get(1);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.refKey</code>.
     */
    public void setRefkey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.refKey</code>.
     */
    public String getRefkey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.displayScheduleId</code>.
     */
    public void setDisplayscheduleid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.displayScheduleId</code>.
     */
    public String getDisplayscheduleid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.debitAccount</code>.
     */
    public void setDebitaccount(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.debitAccount</code>.
     */
    public String getDebitaccount() {
        return (String) get(4);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.creditAccount</code>.
     */
    public void setCreditaccount(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.creditAccount</code>.
     */
    public String getCreditaccount() {
        return (String) get(5);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.cardNumber</code>.
     */
    public void setCardnumber(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.cardNumber</code>.
     */
    public String getCardnumber() {
        return (String) get(6);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.creditName</code>.
     */
    public void setCreditname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.creditName</code>.
     */
    public String getCreditname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.transactionAmount</code>.
     */
    public void setTransactionamount(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.transactionAmount</code>.
     */
    public String getTransactionamount() {
        return (String) get(8);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.transactionCurrency</code>.
     */
    public void setTransactioncurrency(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.transactionCurrency</code>.
     */
    public String getTransactioncurrency() {
        return (String) get(9);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.transactionDetail</code>.
     */
    public void setTransactiondetail(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.transactionDetail</code>.
     */
    public String getTransactiondetail() {
        return (String) get(10);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.chargeAccount</code>.
     */
    public void setChargeaccount(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.chargeAccount</code>.
     */
    public String getChargeaccount() {
        return (String) get(11);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.cityCode</code>.
     */
    public void setCitycode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.cityCode</code>.
     */
    public String getCitycode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.bankCode</code>.
     */
    public void setBankcode(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.bankCode</code>.
     */
    public String getBankcode() {
        return (String) get(13);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.branchCode</code>.
     */
    public void setBranchcode(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.branchCode</code>.
     */
    public String getBranchcode() {
        return (String) get(14);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.typeDescription</code>.
     */
    public void setTypedescription(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.typeDescription</code>.
     */
    public Integer getTypedescription() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.feeId</code>.
     */
    public void setFeeid(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.feeId</code>.
     */
    public Integer getFeeid() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.beginDate</code>.
     */
    public void setBegindate(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.beginDate</code>.
     */
    public Long getBegindate() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.nextDate</code>.
     */
    public void setNextdate(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.nextDate</code>.
     */
    public Long getNextdate() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>transaction.updatePaymentSchedule.autoRepeat</code>.
     */
    public void setAutorepeat(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>transaction.updatePaymentSchedule.autoRepeat</code>.
     */
    public Integer getAutorepeat() {
        return (Integer) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Integer, Integer, Long, Long, Integer> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Integer, Integer, Long, Long, Integer> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.CIF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.REFKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.DISPLAYSCHEDULEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.DEBITACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.CREDITACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.CARDNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.CREDITNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.TRANSACTIONAMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.TRANSACTIONCURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.TRANSACTIONDETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.CHARGEACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.CITYCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.BANKCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.BRANCHCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.TYPEDESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.FEEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.BEGINDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field19() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.NEXTDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field20() {
        return Updatepaymentschedule.UPDATEPAYMENTSCHEDULE.AUTOREPEAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRefkey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDisplayscheduleid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDebitaccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreditaccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCardnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCreditname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getTransactionamount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getTransactioncurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getTransactiondetail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getChargeaccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCitycode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getBankcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getBranchcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getTypedescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getFeeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getBegindate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value19() {
        return getNextdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value20() {
        return getAutorepeat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value2(String value) {
        setCif(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value3(String value) {
        setRefkey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value4(String value) {
        setDisplayscheduleid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value5(String value) {
        setDebitaccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value6(String value) {
        setCreditaccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value7(String value) {
        setCardnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value8(String value) {
        setCreditname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value9(String value) {
        setTransactionamount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value10(String value) {
        setTransactioncurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value11(String value) {
        setTransactiondetail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value12(String value) {
        setChargeaccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value13(String value) {
        setCitycode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value14(String value) {
        setBankcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value15(String value) {
        setBranchcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value16(Integer value) {
        setTypedescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value17(Integer value) {
        setFeeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value18(Long value) {
        setBegindate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value19(Long value) {
        setNextdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord value20(Integer value) {
        setAutorepeat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UpdatepaymentscheduleRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, Integer value16, Integer value17, Long value18, Long value19, Integer value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UpdatepaymentscheduleRecord
     */
    public UpdatepaymentscheduleRecord() {
        super(Updatepaymentschedule.UPDATEPAYMENTSCHEDULE);
    }

    /**
     * Create a detached, initialised UpdatepaymentscheduleRecord
     */
    public UpdatepaymentscheduleRecord(Integer id, String cif, String refkey, String displayscheduleid, String debitaccount, String creditaccount, String cardnumber, String creditname, String transactionamount, String transactioncurrency, String transactiondetail, String chargeaccount, String citycode, String bankcode, String branchcode, Integer typedescription, Integer feeid, Long begindate, Long nextdate, Integer autorepeat) {
        super(Updatepaymentschedule.UPDATEPAYMENTSCHEDULE);

        set(0, id);
        set(1, cif);
        set(2, refkey);
        set(3, displayscheduleid);
        set(4, debitaccount);
        set(5, creditaccount);
        set(6, cardnumber);
        set(7, creditname);
        set(8, transactionamount);
        set(9, transactioncurrency);
        set(10, transactiondetail);
        set(11, chargeaccount);
        set(12, citycode);
        set(13, bankcode);
        set(14, branchcode);
        set(15, typedescription);
        set(16, feeid);
        set(17, begindate);
        set(18, nextdate);
        set(19, autorepeat);
    }
}
