/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jooqDemo.model.tables.Cardverify;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardverifyRecord extends UpdatableRecordImpl<CardverifyRecord> implements Record6<String, String, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -608525672;

    /**
     * Setter for <code>account.cardVerify.refKey</code>.
     */
    public void setRefkey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.cardVerify.refKey</code>.
     */
    public String getRefkey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>account.cardVerify.cardNumber</code>.
     */
    public void setCardnumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.cardVerify.cardNumber</code>.
     */
    public String getCardnumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>account.cardVerify.verifyOTP</code>.
     */
    public void setVerifyotp(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.cardVerify.verifyOTP</code>.
     */
    public Integer getVerifyotp() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>account.cardVerify.status</code>.
     */
    public void setStatus(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.cardVerify.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>account.cardVerify.modifiedAt</code>.
     */
    public void setModifiedat(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.cardVerify.modifiedAt</code>.
     */
    public Timestamp getModifiedat() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>account.cardVerify.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.cardVerify.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Cardverify.CARDVERIFY.REFKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Cardverify.CARDVERIFY.CARDNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Cardverify.CARDVERIFY.VERIFYOTP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Cardverify.CARDVERIFY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Cardverify.CARDVERIFY.MODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Cardverify.CARDVERIFY.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRefkey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCardnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getVerifyotp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getModifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardverifyRecord value1(String value) {
        setRefkey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardverifyRecord value2(String value) {
        setCardnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardverifyRecord value3(Integer value) {
        setVerifyotp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardverifyRecord value4(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardverifyRecord value5(Timestamp value) {
        setModifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardverifyRecord value6(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardverifyRecord values(String value1, String value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CardverifyRecord
     */
    public CardverifyRecord() {
        super(Cardverify.CARDVERIFY);
    }

    /**
     * Create a detached, initialised CardverifyRecord
     */
    public CardverifyRecord(String refkey, String cardnumber, Integer verifyotp, Integer status, Timestamp modifiedat, Timestamp createdat) {
        super(Cardverify.CARDVERIFY);

        set(0, refkey);
        set(1, cardnumber);
        set(2, verifyotp);
        set(3, status);
        set(4, modifiedat);
        set(5, createdat);
    }
}
