/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model.tables.records;


import jooqDemo.model.tables.Card;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardRecord extends UpdatableRecordImpl<CardRecord> implements Record12<String, String, String, String, Date, Date, Integer, Integer, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -345043867;

    /**
     * Setter for <code>account.card.cardNumber</code>.
     */
    public void setCardnumber(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.card.cardNumber</code>.
     */
    public String getCardnumber() {
        return (String) get(0);
    }

    /**
     * Setter for <code>account.card.accountNumber</code>.
     */
    public void setAccountnumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.card.accountNumber</code>.
     */
    public String getAccountnumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>account.card.cardName</code>.
     */
    public void setCardname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.card.cardName</code>.
     */
    public String getCardname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>account.card.embossingName</code>.
     */
    public void setEmbossingname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.card.embossingName</code>.
     */
    public String getEmbossingname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>account.card.dateIssue</code>.
     */
    public void setDateissue(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.card.dateIssue</code>.
     */
    public Date getDateissue() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>account.card.dateExpires</code>.
     */
    public void setDateexpires(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.card.dateExpires</code>.
     */
    public Date getDateexpires() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>account.card.status</code>.
     */
    public void setStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>account.card.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>account.card.preStatus</code>.
     */
    public void setPrestatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>account.card.preStatus</code>.
     */
    public Integer getPrestatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>account.card.cardType</code>.
     */
    public void setCardtype(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>account.card.cardType</code>.
     */
    public Integer getCardtype() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>account.card.ecomerceStatus</code>.
     */
    public void setEcomercestatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>account.card.ecomerceStatus</code>.
     */
    public Integer getEcomercestatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>account.card.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>account.card.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>account.card.modifiedAt</code>.
     */
    public void setModifiedat(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>account.card.modifiedAt</code>.
     */
    public Timestamp getModifiedat() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, Date, Date, Integer, Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, Date, Date, Integer, Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Card.CARD.CARDNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Card.CARD.ACCOUNTNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Card.CARD.CARDNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Card.CARD.EMBOSSINGNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Card.CARD.DATEISSUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return Card.CARD.DATEEXPIRES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Card.CARD.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Card.CARD.PRESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Card.CARD.CARDTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Card.CARD.ECOMERCESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Card.CARD.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Card.CARD.MODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getCardnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccountnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCardname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmbossingname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getDateissue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getDateexpires();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPrestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getCardtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getEcomercestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getModifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value1(String value) {
        setCardnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value2(String value) {
        setAccountnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value3(String value) {
        setCardname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value4(String value) {
        setEmbossingname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value5(Date value) {
        setDateissue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value6(Date value) {
        setDateexpires(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value7(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value8(Integer value) {
        setPrestatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value9(Integer value) {
        setCardtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value10(Integer value) {
        setEcomercestatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value11(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord value12(Timestamp value) {
        setModifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CardRecord values(String value1, String value2, String value3, String value4, Date value5, Date value6, Integer value7, Integer value8, Integer value9, Integer value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CardRecord
     */
    public CardRecord() {
        super(Card.CARD);
    }

    /**
     * Create a detached, initialised CardRecord
     */
    public CardRecord(String cardnumber, String accountnumber, String cardname, String embossingname, Date dateissue, Date dateexpires, Integer status, Integer prestatus, Integer cardtype, Integer ecomercestatus, Timestamp createdat, Timestamp modifiedat) {
        super(Card.CARD);

        set(0, cardnumber);
        set(1, accountnumber);
        set(2, cardname);
        set(3, embossingname);
        set(4, dateissue);
        set(5, dateexpires);
        set(6, status);
        set(7, prestatus);
        set(8, cardtype);
        set(9, ecomercestatus);
        set(10, createdat);
        set(11, modifiedat);
    }
}
