/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import jooqDemo.model.tables.Ddaccount;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DdaccountRecord extends UpdatableRecordImpl<DdaccountRecord> implements Record20<Integer, String, String, String, String, String, BigDecimal, BigDecimal, Integer, Integer, String, Timestamp, Timestamp, Timestamp, BigDecimal, BigDecimal, BigDecimal, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 1913828801;

    /**
     * Setter for <code>account.ddAccount.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.ddAccount.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>account.ddAccount.accountNumber</code>.
     */
    public void setAccountnumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.ddAccount.accountNumber</code>.
     */
    public String getAccountnumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>account.ddAccount.displayAccount</code>.
     */
    public void setDisplayaccount(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.ddAccount.displayAccount</code>.
     */
    public String getDisplayaccount() {
        return (String) get(2);
    }

    /**
     * Setter for <code>account.ddAccount.accountRefNo</code>.
     */
    public void setAccountrefno(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.ddAccount.accountRefNo</code>.
     */
    public String getAccountrefno() {
        return (String) get(3);
    }

    /**
     * Setter for <code>account.ddAccount.accountType</code>.
     */
    public void setAccounttype(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.ddAccount.accountType</code>.
     */
    public String getAccounttype() {
        return (String) get(4);
    }

    /**
     * Setter for <code>account.ddAccount.cif</code>.
     */
    public void setCif(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.ddAccount.cif</code>.
     */
    public String getCif() {
        return (String) get(5);
    }

    /**
     * Setter for <code>account.ddAccount.balance</code>.
     */
    public void setBalance(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>account.ddAccount.balance</code>.
     */
    public BigDecimal getBalance() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>account.ddAccount.preBalance</code>.
     */
    public void setPrebalance(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>account.ddAccount.preBalance</code>.
     */
    public BigDecimal getPrebalance() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>account.ddAccount.status</code>.
     */
    public void setStatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>account.ddAccount.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>account.ddAccount.preStatus</code>.
     */
    public void setPrestatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>account.ddAccount.preStatus</code>.
     */
    public Integer getPrestatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>account.ddAccount.currency</code>.
     */
    public void setCurrency(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>account.ddAccount.currency</code>.
     */
    public String getCurrency() {
        return (String) get(10);
    }

    /**
     * Setter for <code>account.ddAccount.openAt</code>.
     */
    public void setOpenat(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>account.ddAccount.openAt</code>.
     */
    public Timestamp getOpenat() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>account.ddAccount.closeAt</code>.
     */
    public void setCloseat(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>account.ddAccount.closeAt</code>.
     */
    public Timestamp getCloseat() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>account.ddAccount.lastUseAt</code>.
     */
    public void setLastuseat(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>account.ddAccount.lastUseAt</code>.
     */
    public Timestamp getLastuseat() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>account.ddAccount.accruedInterest</code>.
     */
    public void setAccruedinterest(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>account.ddAccount.accruedInterest</code>.
     */
    public BigDecimal getAccruedinterest() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>account.ddAccount.accruedExpenses</code>.
     */
    public void setAccruedexpenses(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>account.ddAccount.accruedExpenses</code>.
     */
    public BigDecimal getAccruedexpenses() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>account.ddAccount.accruedInCome</code>.
     */
    public void setAccruedincome(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>account.ddAccount.accruedInCome</code>.
     */
    public BigDecimal getAccruedincome() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>account.ddAccount.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>account.ddAccount.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>account.ddAccount.modifiedAt</code>.
     */
    public void setModifiedat(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>account.ddAccount.modifiedAt</code>.
     */
    public Timestamp getModifiedat() {
        return (Timestamp) get(18);
    }

    /**
     * Setter for <code>account.ddAccount.branchID</code>.
     */
    public void setBranchid(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>account.ddAccount.branchID</code>.
     */
    public String getBranchid() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Integer, String, String, String, String, String, BigDecimal, BigDecimal, Integer, Integer, String, Timestamp, Timestamp, Timestamp, BigDecimal, BigDecimal, BigDecimal, Timestamp, Timestamp, String> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Integer, String, String, String, String, String, BigDecimal, BigDecimal, Integer, Integer, String, Timestamp, Timestamp, Timestamp, BigDecimal, BigDecimal, BigDecimal, Timestamp, Timestamp, String> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Ddaccount.DDACCOUNT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Ddaccount.DDACCOUNT.ACCOUNTNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Ddaccount.DDACCOUNT.DISPLAYACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Ddaccount.DDACCOUNT.ACCOUNTREFNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Ddaccount.DDACCOUNT.ACCOUNTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Ddaccount.DDACCOUNT.CIF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return Ddaccount.DDACCOUNT.BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return Ddaccount.DDACCOUNT.PREBALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Ddaccount.DDACCOUNT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Ddaccount.DDACCOUNT.PRESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Ddaccount.DDACCOUNT.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Ddaccount.DDACCOUNT.OPENAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return Ddaccount.DDACCOUNT.CLOSEAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return Ddaccount.DDACCOUNT.LASTUSEAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field15() {
        return Ddaccount.DDACCOUNT.ACCRUEDINTEREST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field16() {
        return Ddaccount.DDACCOUNT.ACCRUEDEXPENSES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field17() {
        return Ddaccount.DDACCOUNT.ACCRUEDINCOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return Ddaccount.DDACCOUNT.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field19() {
        return Ddaccount.DDACCOUNT.MODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return Ddaccount.DDACCOUNT.BRANCHID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccountnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDisplayaccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAccountrefno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAccounttype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getPrebalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPrestatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getOpenat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getCloseat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getLastuseat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value15() {
        return getAccruedinterest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value16() {
        return getAccruedexpenses();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value17() {
        return getAccruedincome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value19() {
        return getModifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getBranchid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value2(String value) {
        setAccountnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value3(String value) {
        setDisplayaccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value4(String value) {
        setAccountrefno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value5(String value) {
        setAccounttype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value6(String value) {
        setCif(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value7(BigDecimal value) {
        setBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value8(BigDecimal value) {
        setPrebalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value9(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value10(Integer value) {
        setPrestatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value11(String value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value12(Timestamp value) {
        setOpenat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value13(Timestamp value) {
        setCloseat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value14(Timestamp value) {
        setLastuseat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value15(BigDecimal value) {
        setAccruedinterest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value16(BigDecimal value) {
        setAccruedexpenses(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value17(BigDecimal value) {
        setAccruedincome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value18(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value19(Timestamp value) {
        setModifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord value20(String value) {
        setBranchid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdaccountRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, BigDecimal value7, BigDecimal value8, Integer value9, Integer value10, String value11, Timestamp value12, Timestamp value13, Timestamp value14, BigDecimal value15, BigDecimal value16, BigDecimal value17, Timestamp value18, Timestamp value19, String value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DdaccountRecord
     */
    public DdaccountRecord() {
        super(Ddaccount.DDACCOUNT);
    }

    /**
     * Create a detached, initialised DdaccountRecord
     */
    public DdaccountRecord(Integer id, String accountnumber, String displayaccount, String accountrefno, String accounttype, String cif, BigDecimal balance, BigDecimal prebalance, Integer status, Integer prestatus, String currency, Timestamp openat, Timestamp closeat, Timestamp lastuseat, BigDecimal accruedinterest, BigDecimal accruedexpenses, BigDecimal accruedincome, Timestamp createdat, Timestamp modifiedat, String branchid) {
        super(Ddaccount.DDACCOUNT);

        set(0, id);
        set(1, accountnumber);
        set(2, displayaccount);
        set(3, accountrefno);
        set(4, accounttype);
        set(5, cif);
        set(6, balance);
        set(7, prebalance);
        set(8, status);
        set(9, prestatus);
        set(10, currency);
        set(11, openat);
        set(12, closeat);
        set(13, lastuseat);
        set(14, accruedinterest);
        set(15, accruedexpenses);
        set(16, accruedincome);
        set(17, createdat);
        set(18, modifiedat);
        set(19, branchid);
    }
}
