/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model.tables.records;


import jooqDemo.model.tables.Ddrate;
import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DdrateRecord extends TableRecordImpl<DdrateRecord> implements Record10<String, BigDecimal, BigDecimal, BigDecimal, String, Integer, Timestamp, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -146001454;

    /**
     * Setter for <code>account.ddRate.accountType</code>.
     */
    public void setAccounttype(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.ddRate.accountType</code>.
     */
    public String getAccounttype() {
        return (String) get(0);
    }

    /**
     * Setter for <code>account.ddRate.fromAmount</code>.
     */
    public void setFromamount(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.ddRate.fromAmount</code>.
     */
    public BigDecimal getFromamount() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>account.ddRate.toAmount</code>.
     */
    public void setToamount(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.ddRate.toAmount</code>.
     */
    public BigDecimal getToamount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>account.ddRate.rate</code>.
     */
    public void setRate(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.ddRate.rate</code>.
     */
    public BigDecimal getRate() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>account.ddRate.administrators</code>.
     */
    public void setAdministrators(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.ddRate.administrators</code>.
     */
    public String getAdministrators() {
        return (String) get(4);
    }

    /**
     * Setter for <code>account.ddRate.status</code>.
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.ddRate.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>account.ddRate.startAt</code>.
     */
    public void setStartat(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>account.ddRate.startAt</code>.
     */
    public Timestamp getStartat() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>account.ddRate.endAt</code>.
     */
    public void setEndat(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>account.ddRate.endAt</code>.
     */
    public Timestamp getEndat() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>account.ddRate.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>account.ddRate.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>account.ddRate.modifiedAt</code>.
     */
    public void setModifiedat(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>account.ddRate.modifiedAt</code>.
     */
    public Timestamp getModifiedat() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, BigDecimal, BigDecimal, BigDecimal, String, Integer, Timestamp, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, BigDecimal, BigDecimal, BigDecimal, String, Integer, Timestamp, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Ddrate.DDRATE.ACCOUNTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return Ddrate.DDRATE.FROMAMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Ddrate.DDRATE.TOAMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Ddrate.DDRATE.RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Ddrate.DDRATE.ADMINISTRATORS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Ddrate.DDRATE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Ddrate.DDRATE.STARTAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Ddrate.DDRATE.ENDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Ddrate.DDRATE.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Ddrate.DDRATE.MODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAccounttype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getFromamount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getToamount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAdministrators();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getStartat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getEndat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getModifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdrateRecord value1(String value) {
        setAccounttype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdrateRecord value2(BigDecimal value) {
        setFromamount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdrateRecord value3(BigDecimal value) {
        setToamount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdrateRecord value4(BigDecimal value) {
        setRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdrateRecord value5(String value) {
        setAdministrators(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdrateRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdrateRecord value7(Timestamp value) {
        setStartat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdrateRecord value8(Timestamp value) {
        setEndat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdrateRecord value9(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdrateRecord value10(Timestamp value) {
        setModifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DdrateRecord values(String value1, BigDecimal value2, BigDecimal value3, BigDecimal value4, String value5, Integer value6, Timestamp value7, Timestamp value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DdrateRecord
     */
    public DdrateRecord() {
        super(Ddrate.DDRATE);
    }

    /**
     * Create a detached, initialised DdrateRecord
     */
    public DdrateRecord(String accounttype, BigDecimal fromamount, BigDecimal toamount, BigDecimal rate, String administrators, Integer status, Timestamp startat, Timestamp endat, Timestamp createdat, Timestamp modifiedat) {
        super(Ddrate.DDRATE);

        set(0, accounttype);
        set(1, fromamount);
        set(2, toamount);
        set(3, rate);
        set(4, administrators);
        set(5, status);
        set(6, startat);
        set(7, endat);
        set(8, createdat);
        set(9, modifiedat);
    }
}
