/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model.tables.records;


import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import jooqDemo.model.tables.Fdaccount;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdaccountRecord extends UpdatableRecordImpl<FdaccountRecord> {

    private static final long serialVersionUID = 1780652420;

    /**
     * Setter for <code>account.fdAccount.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.fdAccount.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>account.fdAccount.fdAccountNumberPk</code>.
     */
    public void setFdaccountnumberpk(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.fdAccount.fdAccountNumberPk</code>.
     */
    public String getFdaccountnumberpk() {
        return (String) get(1);
    }

    /**
     * Setter for <code>account.fdAccount.fdAccountNumber</code>.
     */
    public void setFdaccountnumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.fdAccount.fdAccountNumber</code>.
     */
    public String getFdaccountnumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>account.fdAccount.fdType</code>.
     */
    public void setFdtype(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.fdAccount.fdType</code>.
     */
    public String getFdtype() {
        return (String) get(3);
    }

    /**
     * Setter for <code>account.fdAccount.title</code>.
     */
    public void setTitle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.fdAccount.title</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>account.fdAccount.cif</code>.
     */
    public void setCif(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.fdAccount.cif</code>.
     */
    public String getCif() {
        return (String) get(5);
    }

    /**
     * Setter for <code>account.fdAccount.currency</code>.
     */
    public void setCurrency(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>account.fdAccount.currency</code>.
     */
    public String getCurrency() {
        return (String) get(6);
    }

    /**
     * Setter for <code>account.fdAccount.intRate</code>.
     */
    public void setIntrate(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>account.fdAccount.intRate</code>.
     */
    public BigDecimal getIntrate() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>account.fdAccount.periodPerTerm</code>.
     */
    public void setPeriodperterm(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>account.fdAccount.periodPerTerm</code>.
     */
    public Integer getPeriodperterm() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>account.fdAccount.originalAmount</code>.
     */
    public void setOriginalamount(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>account.fdAccount.originalAmount</code>.
     */
    public BigDecimal getOriginalamount() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>account.fdAccount.withDraw</code>.
     */
    public void setWithdraw(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>account.fdAccount.withDraw</code>.
     */
    public BigDecimal getWithdraw() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>account.fdAccount.interestPerMonth</code>.
     */
    public void setInterestpermonth(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>account.fdAccount.interestPerMonth</code>.
     */
    public BigDecimal getInterestpermonth() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>account.fdAccount.totalInterest</code>.
     */
    public void setTotalinterest(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>account.fdAccount.totalInterest</code>.
     */
    public BigDecimal getTotalinterest() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>account.fdAccount.interestAccrued</code>.
     */
    public void setInterestaccrued(BigDecimal value) {
        set(13, value);
    }

    /**
     * Getter for <code>account.fdAccount.interestAccrued</code>.
     */
    public BigDecimal getInterestaccrued() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>account.fdAccount.interestPay</code>.
     */
    public void setInterestpay(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>account.fdAccount.interestPay</code>.
     */
    public BigDecimal getInterestpay() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>account.fdAccount.interestPaid</code>.
     */
    public void setInterestpaid(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>account.fdAccount.interestPaid</code>.
     */
    public BigDecimal getInterestpaid() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>account.fdAccount.datePaid</code>.
     */
    public void setDatepaid(Date value) {
        set(16, value);
    }

    /**
     * Getter for <code>account.fdAccount.datePaid</code>.
     */
    public Date getDatepaid() {
        return (Date) get(16);
    }

    /**
     * Setter for <code>account.fdAccount.receiveAcc</code>.
     */
    public void setReceiveacc(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>account.fdAccount.receiveAcc</code>.
     */
    public String getReceiveacc() {
        return (String) get(17);
    }

    /**
     * Setter for <code>account.fdAccount.autoReceiveType</code>.
     */
    public void setAutoreceivetype(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>account.fdAccount.autoReceiveType</code>.
     */
    public String getAutoreceivetype() {
        return (String) get(18);
    }

    /**
     * Setter for <code>account.fdAccount.autoCompoundInt</code>.
     */
    public void setAutocompoundint(Byte value) {
        set(19, value);
    }

    /**
     * Getter for <code>account.fdAccount.autoCompoundInt</code>.
     */
    public Byte getAutocompoundint() {
        return (Byte) get(19);
    }

    /**
     * Setter for <code>account.fdAccount.fromDate</code>.
     */
    public void setFromdate(Date value) {
        set(20, value);
    }

    /**
     * Getter for <code>account.fdAccount.fromDate</code>.
     */
    public Date getFromdate() {
        return (Date) get(20);
    }

    /**
     * Setter for <code>account.fdAccount.toDate</code>.
     */
    public void setTodate(Date value) {
        set(21, value);
    }

    /**
     * Getter for <code>account.fdAccount.toDate</code>.
     */
    public Date getTodate() {
        return (Date) get(21);
    }

    /**
     * Setter for <code>account.fdAccount.nextGSPayDate</code>.
     */
    public void setNextgspaydate(Date value) {
        set(22, value);
    }

    /**
     * Getter for <code>account.fdAccount.nextGSPayDate</code>.
     */
    public Date getNextgspaydate() {
        return (Date) get(22);
    }

    /**
     * Setter for <code>account.fdAccount.goalSave</code>.
     */
    public void setGoalsave(Byte value) {
        set(23, value);
    }

    /**
     * Getter for <code>account.fdAccount.goalSave</code>.
     */
    public Byte getGoalsave() {
        return (Byte) get(23);
    }

    /**
     * Setter for <code>account.fdAccount.autoAccrue</code>.
     */
    public void setAutoaccrue(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>account.fdAccount.autoAccrue</code>.
     */
    public Integer getAutoaccrue() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>account.fdAccount.image</code>.
     */
    public void setImage(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>account.fdAccount.image</code>.
     */
    public String getImage() {
        return (String) get(25);
    }

    /**
     * Setter for <code>account.fdAccount.createDate</code>.
     */
    public void setCreatedate(Date value) {
        set(26, value);
    }

    /**
     * Getter for <code>account.fdAccount.createDate</code>.
     */
    public Date getCreatedate() {
        return (Date) get(26);
    }

    /**
     * Setter for <code>account.fdAccount.prstatus</code>.
     */
    public void setPrstatus(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>account.fdAccount.prstatus</code>.
     */
    public Integer getPrstatus() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>account.fdAccount.status</code>.
     */
    public void setStatus(Integer value) {
        set(28, value);
    }

    /**
     * Getter for <code>account.fdAccount.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(28);
    }

    /**
     * Setter for <code>account.fdAccount.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(29, value);
    }

    /**
     * Getter for <code>account.fdAccount.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(29);
    }

    /**
     * Setter for <code>account.fdAccount.modifyAt</code>.
     */
    public void setModifyat(Timestamp value) {
        set(30, value);
    }

    /**
     * Getter for <code>account.fdAccount.modifyAt</code>.
     */
    public Timestamp getModifyat() {
        return (Timestamp) get(30);
    }

    /**
     * Setter for <code>account.fdAccount.accountRefNo</code>.
     */
    public void setAccountrefno(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>account.fdAccount.accountRefNo</code>.
     */
    public String getAccountrefno() {
        return (String) get(31);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FdaccountRecord
     */
    public FdaccountRecord() {
        super(Fdaccount.FDACCOUNT);
    }

    /**
     * Create a detached, initialised FdaccountRecord
     */
    public FdaccountRecord(Integer id, String fdaccountnumberpk, String fdaccountnumber, String fdtype, String title, String cif, String currency, BigDecimal intrate, Integer periodperterm, BigDecimal originalamount, BigDecimal withdraw, BigDecimal interestpermonth, BigDecimal totalinterest, BigDecimal interestaccrued, BigDecimal interestpay, BigDecimal interestpaid, Date datepaid, String receiveacc, String autoreceivetype, Byte autocompoundint, Date fromdate, Date todate, Date nextgspaydate, Byte goalsave, Integer autoaccrue, String image, Date createdate, Integer prstatus, Integer status, Timestamp createdat, Timestamp modifyat, String accountrefno) {
        super(Fdaccount.FDACCOUNT);

        set(0, id);
        set(1, fdaccountnumberpk);
        set(2, fdaccountnumber);
        set(3, fdtype);
        set(4, title);
        set(5, cif);
        set(6, currency);
        set(7, intrate);
        set(8, periodperterm);
        set(9, originalamount);
        set(10, withdraw);
        set(11, interestpermonth);
        set(12, totalinterest);
        set(13, interestaccrued);
        set(14, interestpay);
        set(15, interestpaid);
        set(16, datepaid);
        set(17, receiveacc);
        set(18, autoreceivetype);
        set(19, autocompoundint);
        set(20, fromdate);
        set(21, todate);
        set(22, nextgspaydate);
        set(23, goalsave);
        set(24, autoaccrue);
        set(25, image);
        set(26, createdate);
        set(27, prstatus);
        set(28, status);
        set(29, createdat);
        set(30, modifyat);
        set(31, accountrefno);
    }
}
