/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model.tables.records;


import javax.annotation.Generated;

import jooqDemo.model.tables.Payee;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayeeRecord extends UpdatableRecordImpl<PayeeRecord> implements Record9<String, String, String, String, String, Integer, String, Long, Long> {

    private static final long serialVersionUID = -923698400;

    /**
     * Setter for <code>account.payee.payeeId</code>.
     */
    public void setPayeeid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.payee.payeeId</code>.
     */
    public String getPayeeid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>account.payee.fullName</code>.
     */
    public void setFullname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.payee.fullName</code>.
     */
    public String getFullname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>account.payee.phone</code>.
     */
    public void setPhone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.payee.phone</code>.
     */
    public String getPhone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>account.payee.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.payee.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>account.payee.avatar</code>.
     */
    public void setAvatar(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.payee.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(4);
    }

    /**
     * Setter for <code>account.payee.status</code>.
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.payee.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>account.payee.cif</code>.
     */
    public void setCif(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>account.payee.cif</code>.
     */
    public String getCif() {
        return (String) get(6);
    }

    /**
     * Setter for <code>account.payee.modifiedAt</code>.
     */
    public void setModifiedat(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>account.payee.modifiedAt</code>.
     */
    public Long getModifiedat() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>account.payee.createdAt</code>.
     */
    public void setCreatedat(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>account.payee.createdAt</code>.
     */
    public Long getCreatedat() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, String, Integer, String, Long, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, String, Integer, String, Long, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Payee.PAYEE.PAYEEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Payee.PAYEE.FULLNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Payee.PAYEE.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Payee.PAYEE.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Payee.PAYEE.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Payee.PAYEE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Payee.PAYEE.CIF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Payee.PAYEE.MODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Payee.PAYEE.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPayeeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFullname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getModifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayeeRecord value1(String value) {
        setPayeeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayeeRecord value2(String value) {
        setFullname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayeeRecord value3(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayeeRecord value4(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayeeRecord value5(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayeeRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayeeRecord value7(String value) {
        setCif(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayeeRecord value8(Long value) {
        setModifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayeeRecord value9(Long value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayeeRecord values(String value1, String value2, String value3, String value4, String value5, Integer value6, String value7, Long value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PayeeRecord
     */
    public PayeeRecord() {
        super(Payee.PAYEE);
    }

    /**
     * Create a detached, initialised PayeeRecord
     */
    public PayeeRecord(String payeeid, String fullname, String phone, String email, String avatar, Integer status, String cif, Long modifiedat, Long createdat) {
        super(Payee.PAYEE);

        set(0, payeeid);
        set(1, fullname);
        set(2, phone);
        set(3, email);
        set(4, avatar);
        set(5, status);
        set(6, cif);
        set(7, modifiedat);
        set(8, createdat);
    }
}
