/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model.tables.records;


import jooqDemo.model.tables.Paymentrequest;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentrequestRecord extends UpdatableRecordImpl<PaymentrequestRecord> implements Record8<String, String, BigDecimal, String, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1583945927;

    /**
     * Setter for <code>account.paymentRequest.refKey</code>.
     */
    public void setRefkey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.paymentRequest.refKey</code>.
     */
    public String getRefkey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>account.paymentRequest.paymentId</code>.
     */
    public void setPaymentid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.paymentRequest.paymentId</code>.
     */
    public String getPaymentid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>account.paymentRequest.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.paymentRequest.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>account.paymentRequest.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.paymentRequest.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>account.paymentRequest.cif</code>.
     */
    public void setCif(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.paymentRequest.cif</code>.
     */
    public String getCif() {
        return (String) get(4);
    }

    /**
     * Setter for <code>account.paymentRequest.verifyOTP</code>.
     */
    public void setVerifyotp(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.paymentRequest.verifyOTP</code>.
     */
    public Integer getVerifyotp() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>account.paymentRequest.modifiedAt</code>.
     */
    public void setModifiedat(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>account.paymentRequest.modifiedAt</code>.
     */
    public Timestamp getModifiedat() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>account.paymentRequest.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>account.paymentRequest.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, BigDecimal, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, BigDecimal, String, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Paymentrequest.PAYMENTREQUEST.REFKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Paymentrequest.PAYMENTREQUEST.PAYMENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Paymentrequest.PAYMENTREQUEST.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Paymentrequest.PAYMENTREQUEST.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Paymentrequest.PAYMENTREQUEST.CIF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Paymentrequest.PAYMENTREQUEST.VERIFYOTP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Paymentrequest.PAYMENTREQUEST.MODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Paymentrequest.PAYMENTREQUEST.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRefkey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPaymentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCif();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getVerifyotp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getModifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentrequestRecord value1(String value) {
        setRefkey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentrequestRecord value2(String value) {
        setPaymentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentrequestRecord value3(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentrequestRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentrequestRecord value5(String value) {
        setCif(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentrequestRecord value6(Integer value) {
        setVerifyotp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentrequestRecord value7(Timestamp value) {
        setModifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentrequestRecord value8(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentrequestRecord values(String value1, String value2, BigDecimal value3, String value4, String value5, Integer value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentrequestRecord
     */
    public PaymentrequestRecord() {
        super(Paymentrequest.PAYMENTREQUEST);
    }

    /**
     * Create a detached, initialised PaymentrequestRecord
     */
    public PaymentrequestRecord(String refkey, String paymentid, BigDecimal amount, String description, String cif, Integer verifyotp, Timestamp modifiedat, Timestamp createdat) {
        super(Paymentrequest.PAYMENTREQUEST);

        set(0, refkey);
        set(1, paymentid);
        set(2, amount);
        set(3, description);
        set(4, cif);
        set(5, verifyotp);
        set(6, modifiedat);
        set(7, createdat);
    }
}
