/*
 * This file is generated by jOOQ.
*/
package jooqDemo.model.tables.records;


import javax.annotation.Generated;

import jooqDemo.model.tables.Payment;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentRecord extends UpdatableRecordImpl<PaymentRecord> implements Record15<String, String, String, String, String, String, String, String, String, String, String, String, Integer, Long, Long> {

    private static final long serialVersionUID = 299614204;

    /**
     * Setter for <code>account.payment.paymentId</code>.
     */
    public void setPaymentid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.payment.paymentId</code>.
     */
    public String getPaymentid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>account.payment.payeeId</code>.
     */
    public void setPayeeid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.payment.payeeId</code>.
     */
    public String getPayeeid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>account.payment.cardNumber</code>.
     */
    public void setCardnumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.payment.cardNumber</code>.
     */
    public String getCardnumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>account.payment.accountNumber</code>.
     */
    public void setAccountnumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.payment.accountNumber</code>.
     */
    public String getAccountnumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>account.payment.accountName</code>.
     */
    public void setAccountname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.payment.accountName</code>.
     */
    public String getAccountname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>account.payment.cardName</code>.
     */
    public void setCardname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.payment.cardName</code>.
     */
    public String getCardname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>account.payment.bankCode</code>.
     */
    public void setBankcode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>account.payment.bankCode</code>.
     */
    public String getBankcode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>account.payment.bankName</code>.
     */
    public void setBankname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>account.payment.bankName</code>.
     */
    public String getBankname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>account.payment.cityCode</code>.
     */
    public void setCitycode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>account.payment.cityCode</code>.
     */
    public String getCitycode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>account.payment.cityName</code>.
     */
    public void setCityname(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>account.payment.cityName</code>.
     */
    public String getCityname() {
        return (String) get(9);
    }

    /**
     * Setter for <code>account.payment.branchCode</code>.
     */
    public void setBranchcode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>account.payment.branchCode</code>.
     */
    public String getBranchcode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>account.payment.branchName</code>.
     */
    public void setBranchname(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>account.payment.branchName</code>.
     */
    public String getBranchname() {
        return (String) get(11);
    }

    /**
     * Setter for <code>account.payment.status</code>.
     */
    public void setStatus(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>account.payment.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>account.payment.modifiedAt</code>.
     */
    public void setModifiedat(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>account.payment.modifiedAt</code>.
     */
    public Long getModifiedat() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>account.payment.createdAt</code>.
     */
    public void setCreatedat(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>account.payment.createdAt</code>.
     */
    public Long getCreatedat() {
        return (Long) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, String, String, String, String, String, String, String, String, Integer, Long, Long> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, String, String, String, String, String, String, String, String, Integer, Long, Long> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Payment.PAYMENT.PAYMENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Payment.PAYMENT.PAYEEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Payment.PAYMENT.CARDNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Payment.PAYMENT.ACCOUNTNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Payment.PAYMENT.ACCOUNTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Payment.PAYMENT.CARDNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Payment.PAYMENT.BANKCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Payment.PAYMENT.BANKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Payment.PAYMENT.CITYCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Payment.PAYMENT.CITYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Payment.PAYMENT.BRANCHCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Payment.PAYMENT.BRANCHNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Payment.PAYMENT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return Payment.PAYMENT.MODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field15() {
        return Payment.PAYMENT.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPaymentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPayeeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCardnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAccountnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAccountname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCardname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getBankcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getBankname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCitycode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCityname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getBranchcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getBranchname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getModifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value15() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value1(String value) {
        setPaymentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value2(String value) {
        setPayeeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value3(String value) {
        setCardnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value4(String value) {
        setAccountnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value5(String value) {
        setAccountname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value6(String value) {
        setCardname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value7(String value) {
        setBankcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value8(String value) {
        setBankname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value9(String value) {
        setCitycode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value10(String value) {
        setCityname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value11(String value) {
        setBranchcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value12(String value) {
        setBranchname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value13(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value14(Long value) {
        setModifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value15(Long value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Integer value13, Long value14, Long value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentRecord
     */
    public PaymentRecord() {
        super(Payment.PAYMENT);
    }

    /**
     * Create a detached, initialised PaymentRecord
     */
    public PaymentRecord(String paymentid, String payeeid, String cardnumber, String accountnumber, String accountname, String cardname, String bankcode, String bankname, String citycode, String cityname, String branchcode, String branchname, Integer status, Long modifiedat, Long createdat) {
        super(Payment.PAYMENT);

        set(0, paymentid);
        set(1, payeeid);
        set(2, cardnumber);
        set(3, accountnumber);
        set(4, accountname);
        set(5, cardname);
        set(6, bankcode);
        set(7, bankname);
        set(8, citycode);
        set(9, cityname);
        set(10, branchcode);
        set(11, branchname);
        set(12, status);
        set(13, modifiedat);
        set(14, createdat);
    }
}
